openapi: 3.0.3
info:
  title: User Service API
  description: |
    User management service for multi-tenant POS system.
    Handles user CRUD operations, invitations, and role management.
  version: 1.0.0

servers:
  - url: http://localhost:8002
    description: Local development
  - url: https://api.example.com/users
    description: Production

tags:
  - name: Users
    description: User management operations
  - name: Invitations
    description: User invitation operations

paths:
  /users:
    get:
      tags:
        - Users
      summary: List users in tenant
      description: Get paginated list of users for the authenticated user's tenant
      operationId: listUsers
      security:
        - cookieAuth: []
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [active, invited, suspended, deleted]
          description: Filter by user status
        - name: role
          in: query
          schema:
            type: string
            enum: [owner, manager, cashier]
          description: Filter by user role
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Items per page
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserListResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      tags:
        - Users
      summary: Create user (internal)
      description: |
        Create new user account. Used by invitation acceptance flow.
        Requires manager or owner role.
      operationId: createUser
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users/{userId}:
    get:
      tags:
        - Users
      summary: Get user by ID
      description: Retrieve user details (tenant-scoped)
      operationId: getUser
      security:
        - cookieAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: User ID (UUID)
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found in tenant
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    patch:
      tags:
        - Users
      summary: Update user
      description: |
        Update user details. Users can update their own profile.
        Owners/managers can update team members.
      operationId: updateUser
      security:
        - cookieAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      tags:
        - Users
      summary: Delete user
      description: |
        Soft delete user (sets status to deleted).
        Cannot delete last owner of tenant.
        Requires owner role.
      operationId: deleteUser
      security:
        - cookieAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User deleted successfully
        '400':
          description: Cannot delete last owner
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - owner role required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users/{userId}/locale:
    patch:
      tags:
        - Users
      summary: Update user locale preference
      description: |
        Update user's preferred language. Users can only update their own locale.
        Used by language switcher component.
      operationId: updateUserLocale
      security:
        - cookieAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: User ID (UUID) - must match authenticated user
        - name: Accept-Language
          in: header
          required: false
          schema:
            type: string
            enum: [en, id]
          description: Optionally set via header as well
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - locale
              properties:
                locale:
                  type: string
                  enum: [en, id]
                  example: id
      responses:
        '200':
          description: Locale updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  locale:
                    type: string
                    enum: [en, id]
                    example: id
                  message:
                    type: string
                    example: Locale updated successfully
        '400':
          description: Invalid locale value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - can only update own locale
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /invitations:
    get:
      tags:
        - Invitations
      summary: List invitations
      description: Get pending invitations for the tenant
      operationId: listInvitations
      security:
        - cookieAuth: []
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, accepted, expired, revoked]
          description: Filter by invitation status
      responses:
        '200':
          description: List of invitations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvitationListResponse'

    post:
      tags:
        - Invitations
      summary: Create invitation
      description: |
        Invite new user to tenant. Sends invitation email.
        Requires owner or manager role.
      operationId: createInvitation
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInvitationRequest'
      responses:
        '201':
          description: Invitation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invitation'
        '400':
          description: Invalid request (e.g., user already exists)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /invitations/{invitationId}/accept:
    post:
      tags:
        - Invitations
      summary: Accept invitation
      description: |
        Accept invitation and create user account.
        Requires invitation token (public endpoint, no auth).
      operationId: acceptInvitation
      parameters:
        - name: invitationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcceptInvitationRequest'
      responses:
        '200':
          description: Invitation accepted, user created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Account created successfully
                  user:
                    $ref: '#/components/schemas/User'
        '400':
          description: Invalid or expired invitation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /invitations/{invitationId}/revoke:
    post:
      tags:
        - Invitations
      summary: Revoke invitation
      description: Cancel pending invitation
      operationId: revokeInvitation
      security:
        - cookieAuth: []
      parameters:
        - name: invitationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Invitation revoked
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invitation revoked

  /health:
    get:
      tags:
        - Health
      summary: Health check
      operationId: healthCheck
      responses:
        '200':
          description: Service healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: auth_token

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: 507f1f77bcf86cd799439011
        tenantId:
          type: string
          example: 507f1f77bcf86cd799439011
        email:
          type: string
          format: email
          example: user@example.com
        role:
          type: string
          enum: [owner, manager, cashier]
          example: manager
        status:
          type: string
          enum: [active, invited, suspended, deleted]
          example: active
        profile:
          type: object
          properties:
            firstName:
              type: string
              example: John
            lastName:
              type: string
              example: Doe
        locale:
          type: string
          enum: [en, id]
          default: en
          example: en
          description: User's preferred language (English or Indonesian)
        lastLoginAt:
          type: string
          format: date-time
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    UserListResponse:
      type: object
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
        pagination:
          $ref: '#/components/schemas/Pagination'

    CreateUserRequest:
      type: object
      required:
        - email
        - password
        - role
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
          minLength: 8
        role:
          type: string
          enum: [manager, cashier]
        profile:
          type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string

    UpdateUserRequest:
      type: object
      properties:
        role:
          type: string
          enum: [owner, manager, cashier]
        status:
          type: string
          enum: [active, suspended]
        profile:
          type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string
        locale:
          type: string
          enum: [en, id]
          description: User's preferred language

    Invitation:
      type: object
      properties:
        id:
          type: string
          example: 507f1f77bcf86cd799439011
        tenantId:
          type: string
        email:
          type: string
          format: email
        role:
          type: string
          enum: [manager, cashier]
        status:
          type: string
          enum: [pending, accepted, expired, revoked]
        invitedBy:
          type: string
          description: User ID who sent invitation
        expiresAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time

    InvitationListResponse:
      type: object
      properties:
        invitations:
          type: array
          items:
            $ref: '#/components/schemas/Invitation'

    CreateInvitationRequest:
      type: object
      required:
        - email
        - role
      properties:
        email:
          type: string
          format: email
        role:
          type: string
          enum: [manager, cashier]

    AcceptInvitationRequest:
      type: object
      required:
        - token
        - password
      properties:
        token:
          type: string
          description: Invitation token from email
        password:
          type: string
          format: password
          minLength: 8
        profile:
          type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string

    Pagination:
      type: object
      properties:
        page:
          type: integer
          example: 1
        limit:
          type: integer
          example: 20
        total:
          type: integer
          example: 45
        totalPages:
          type: integer
          example: 3

    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            details:
              type: object

    HealthResponse:
      type: object
      properties:
        status:
          type: string
          enum: [ok, degraded, down]
        timestamp:
          type: string
          format: date-time
        dependencies:
          type: object
          properties:
            postgresql:
              type: string
              enum: [ok, down]
